BLOCKSIZE = 5
HOST = 'localhost'
PORT = 8000
REWARD = 5
QUEUE_HOST = 'localhost'
QUEUE_PORT = 9000
ILP_NOT_FOUND = 'ERR_2'
SUCCESS = 'SUCCESS'
INVALID_TRANSACTION = 'ERR_3'
HARDNESS = 2
INVALID_NONCE_OR_POW = 'ERR_4'
EMPTY_CHAIN = 'ERR_5'

# For the Queue
FAILURE = 'FAILURE'
NOT_TOP_ILP = 'NOT_TOP_ILP'
TIMEOUT = 'TIMEOUT'
NO_VERIFIERS = 'NO_VERIFIERS'